PREFIX bks:     <http://mu.semte.ch/services/github/madnificent/book-service/books/>
PREFIX schm:    <http://schema.org/>
PREFIX nfo:     <http://www.semanticdesktop.org/ontologies/2007/03/22/nfo#>
PREFIX nie:     <http://www.semanticdesktop.org/ontologies/2007/01/19/nie#>
PREFIX dct:     <http://purl.org/dc/terms/>
PREFIX dbpedia: <http://dbpedia.org/ontology/>
PREFIX de:      <http://mu.semte.ch/vocabularies/delta/>

# Select all from specific graph

SELECT *
WHERE {
	GRAPH <http://mu.semte.ch/graphs/public> {
    ?s ?p ?o .
	}
}

# Select all books

SELECT *
WHERE {
	GRAPH ?g {
		?s ?p schm:Book .
	}
}

# Remove all books

DELETE {
	GRAPH ?g {
		?s ?p ?o .
	}
}
WHERE {
	GRAPH ?g {
		?s ?p ?o .
		?s a schm:Book .
	}
}

# Select all Files

SELECT ?g ?name
WHERE {
	GRAPH ?g {
		?s ?p nfo:FileDataObject .
		?s nfo:fileName ?name .
	}
}

# Remove all Files

DELETE {
	GRAPH ?g {
		?s ?p ?o .
	}
}
WHERE {
	GRAPH ?g {
		?s ?p ?o .
		?s a  nfo:FileDataObject .
	}
}

